### ISSUE TITLE
Very weird inconsistent read with different sessions

### ISSUE THREAD

**Issue by jonhyman** [mongoid/moped#201]
We just tracked down a very strange bug that was only happening on our CI build machine which is a Mac Mini.

mongoid.yml looks like this for test environment, but we are using Moped for the writes and reads in this part of our code:

```
test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: appboy_test
      options:
        safe: true
        consistency: :strong
    # conceptually read-only, use this when secondary reads are okay, do not write
    # to this session
    readonly:
      hosts:
        - localhost:27017
      database: appboy_test
      options:
        consistency: :eventual
  options:
    identity_map_enabled: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: false
```

The mongo database is pointed at a mongos with 1 shard, no replicas.

We have a method which inserts code like this:

``` ruby
Mongoid.session(:default).with(:safe => false) do |session|
  collection = session[MyModel.collection_name]
  query = collection.find(...)
  query.upsert(...)
end
```

In my test, we call that method twice. If I then immediately do this:

``` ruby
puts MyModel.with(:session => :readonly).all.to_a
puts MyModel.all.to_a
```

The readonly session incorrectly returns 1 document, whereas the default session correctly returns 2 documents.

On all our development machines (which are much more powerful than a Mac Mini), both return 2 documents. However, on the Mac Mini, it consistently returns 1 document in the readonly session.

I tried updating the readonly session to be identical to default (consistency: strong, safe: true) but it still fails by returning only 1 document. Is there something special about the default session?
