### ISSUE TITLE
Rails 4+ connection "freezing"

### ISSUE THREAD

**Issue by alexbevi** [mongoid/moped#274]
I'm not really sure how best to describe this issue, but it's been going on ever since I started working with Rails 4 and the latest moped/mongoid.

I have a number of apps that I'm using Rails 4.0.3 (and now 4.1.0) and the latest masters of moped and mongoid. When I'm working with a local mongodb instance (localhost - mongodb 2.4, and now 2.6) I have no issues.

`mongoid.yml`

``` yml
default: &default
  sessions:
    default:      
      uri: "mongodb://localhost:27017/database"
      options:
        timeout: 15
        retry_interval: 1
        max_retries: 5
        pool_size: 10

development:
  <<: *default
```

When I change the connection details to reference a "remote" mongodb instance, I start to get periodic connection issues.

`mongoid.yml`

``` yml
default: &default
  sessions:
    default:      
      uri: "mongodb://remote-mongodb-url:27017/database"
      options:
        timeout: 15
        retry_interval: 1
        max_retries: 5
        pool_size: 10

development:
  <<: *default
```

The issue manifests in the following way:

1) The web application becomes completely unresponsive (the request just hangs)
2) The Rails log doesn't indicate anything out of the ordinary (even with Moped and Mongoid log levels set to DEBUG)

ex:

```
Started GET "/accounts" for 172.16.3.180 at 2014-04-23 09:11:34 -0400
Processing by AccountsController#index as HTML
```

I have tried using multiple web servers (Webrick, Puma, Unicorn) and they all experience the same issue.

3) If I force exit the application server (CTRL+C), I see the following:

```
Started GET "/accounts" for 172.16.3.180 at 2014-04-23 09:11:34 -0400
Processing by AccountsController#index as HTML
^C[2014-04-23 09:12:52] INFO  going to shutdown ...
^CExiting
D, [2014-04-23T09:12:53.516499 #4673] DEBUG -- :   MOPED: 168.62.164.129:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 78545.7536ms
Completed 401 Unauthorized in 78638ms
/home/alex/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:25:in `shutdown': undefined method `shutdown' for nil:NilClass (NoMethodError)
```

There is a `401 Unauthorized` in there, which I'm not sure if it is coming from Devise or if it's part of the issue I'm trying to describe.

The weird thing here is if I deploy the application to production (which is on the same server as mongodb and has a `mongoid.yml` connection setup for localhost:27017), I have no issues.

If this is a simple configuration issue, I'd really appreciate someone pointing me in the right direction as I never had issues with mongoid previously :)
