### ISSUE TITLE
MOPED: Could not resolve IP for: <address>

### ISSUE THREAD

**Issue by steve-rodriguez** [mongoid/moped#354]
This issue is happening periodically.    Any settings/configuration changes that can resolve this or is this a true issue?  Looks like network latency or something like that to me, wondering if there are any Mongoid.yml tweeks that can help alleviate this issue:

2015-02-25T09:23:20-07:00 MOPED: Could not resolve IP for: prod-cms-db2:33478 runtime: n/a
2015-02-25T09:26:37-07:00 MOPED: Could not resolve IP for: prod-cms-db1:33478 runtime: n/a
2015-02-25T10:18:03-07:00  MOPED: Could not resolve IP for: prod-cms-db3:33478 runtime: n/a
2015-02-25T10:44:38-07:00  MOPED: Could not resolve IP for: prod-cms-db3:33478 runtime: n/a
2015-02-25T11:09:02-07:00  MOPED: Could not resolve IP for: prod-cms-db2:33478 runtime: n/a

My mongoid.yml for production looks like this:

production:
  sessions:
    default:
      database: edist
      hosts:
        ['qa2-web-db1:33478', 'qa2-web-db2:33478', 'qa2-web-db3:33478']
      options:
        pool_size: 200
        timeout: 20
        retry_interval: 1
        timeout: 15
        max_retries: 20
        refresh_interval: 10

    secondary:
      database: fund
      hosts:
        ['qa2-cms-db1:33478', 'qa2-cms-db2:33478', 'qa2-cms-db3:33478']
      options:
        pool_size: 200
        timeout: 20
        retry_interval: 1
        timeout: 15
        max_retries: 20
        refresh_interval: 10

**Comment by jstejada** [comment]
:+1: 

I am having the same issue, it is happening almost always and it slows down some of my queries considerably.

mi config is as follows:

```
  sessions:
    default:
      uri: <%= ENV['MONGO_URI_STAGING'] %>
      options:
        pool_size: 50
        pool_timeout: 15
        retry_interval: 1
        timeout: 60
        max_retries: 20
        refresh_interval: 30
```
